# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: saiashirwadinformatia/jekyll-bower:v1
before_script:
  - bundle install --path=.bundler-cache
  - npm install -g ftpsync

cache:
  paths:
    - .bower-cache
    - .bower-registry
    - .bundler-cache
    - assets/js/vendor

cache:
  paths:
    - js/vendor

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - ftpsync -l ./public -r / -h $FTP_HOST -u $FTP_USERNAME -s $FTP_PASSWORD
  artifacts:
    paths:
    - public
  only:
  - master