# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: ruby:2.3
before_script:
  - apt-get update
  - apt-get install nodejs npm
  - npm install -g bower

test:
  stage: test
  script:
  - bower install --allow-root
  - gem install jekyll
  - gem install bundler
  - bundle install
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bower install --allow-root
  - gem install jekyll
  - gem install bundler
  - bundle install
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master