# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Project Ideas
email: connect@saiashirwad.com
description: > # this means to ignore newlines until "baseurl:"
  Open Source your Idea and let community start building 
  a new Open Source that benefits the community
baseurl: "/ProjectIdeas" # the subpath of your site, e.g. /blog
url: "https://saiashirwadinformatia.gitlab.io/ProjectIdeas" # the base hostname & protocol for your site
gitlab_url: "https://gitlab.com/SaiAshirwadInformatia/ProjectIdeas"
twitter_username: SaiAshirwadInfo
github_username:  SaiAshirwadInformatia
gitlab_username: SaiAshirwadInformatia
disqus: saiprojectideas
google_analytics: 'UA-54302492-16'

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "bower.json"
  - "js/vendor/owl.carousel/docs_src"

excerpt_separator: <!--more-->

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/posts/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

monthly_archive:
  path:
    - "/archive"